---
- block:
    - name: Check for existing OpCache config files
      find:
        paths: "{{ item }}"
        contains: 'zend_extension(\s+)?=(\s+)?opcache\.so'
      register: php_installed_opcache_confs
      loop: "{{ php_extension_conf_paths }}"

    - name: Remove any non-role-supplied OpCache config files
      file:
        path: "{{ item.1.path }}"
        state: absent
      when: php_opcache_conf_filename != (item.1.path.split('/') | last)
      loop: "{{ php_installed_opcache_confs.results | subelements('files') }}"
      loop_control:
        label: "{{ item.1.path }}"
      notify:
        - __php_webserver_restart
        - __php_fpm_restart

    - name: Ensure OpCache config file is present
      template:
        src: opcache.ini.j2
        dest: "{{ item }}/{{ php_opcache_conf_filename }}"
        owner: root
        group: root
        force: yes
        mode: 0644
      loop: "{{ php_extension_conf_paths }}"
      loop_control:
        label: "{{ item }}/{{ php_opcache_conf_filename }}"
      notify:
        - __php_webserver_restart
        - __php_fpm_restart
  when: php_opcache_enabled | bool

- name: Remove OpCache config file if OpCache is disabled
  file:
    path: "{{ item }}/{{ php_opcache_conf_filename }}"
    state: absent
  loop: "{{ php_extension_conf_paths }}"
  when: not php_opcache_enabled | bool
  notify:
    - __php_webserver_restart
    - __php_fpm_restart
