---
- name: Ensure dependencies are installed
  package:
    name: "{{ item }}"
    state: present 
  loop: "{{ php_packages_extra }}"

- name: Ensure PHP packages are installed
  package:
    name: "{{ item }}"
    state: "{{ php_packages_state }}"
  loop: "{{ php_packages }}"
  notify:
    - __php_webserver_restart
    - __php_fpm_restart
