---
- name: Ensure dependencies are installed
  package:
    name: "{{ item }}"
    update_cache: "{{ php_apt_cache_update }}"
    state: present
  loop: "{{ php_packages_extra }}"

- name: Ensure PHP packages are installed
  package:
    name: "{{ item }}"
    update_cache: "{{ php_apt_cache_update }}"
    state: "{{ php_packages_state }}"
  loop: "{{ php_packages }}"
  notify:
    - __php_webserver_restart
