---
- include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "vars"
      errors: "ignore"
- include_tasks: overwrites.yml

- include_tasks: install.yml
- include_tasks: pecl.yml
- include_tasks: configure.yml
- include_tasks: "{{ lookup('first_found', params, errors='ignore') }}"
  vars:
    params:
      files:
        - "configure-{{ ansible_os_family | lower }}.yml"
      paths:
        - "tasks"
- include_tasks: configure-apcu.yml
- include_tasks: configure-opcache.yml
- include_tasks: configure-fpm.yml
