---
- name: Install PECL libaries
  shell: "yes '' | {{ php_pecl_executable }} install {{ item }}"
  loop: "{{ php_pecl_modules }}"
  register: pecl_result
  changed_when: "pecl_result.rc == 0"
  failed_when: "not (('already installed' in pecl_result.stdout) or ('install ok:' in pecl_result.stdout))"
